echo "Conchologia-v.0.0.30 - Glossary of Shell Commands"
echo "Each command has either a "
echo "Help Topic, Info Document and/or Man Page."
echo "Type ''help'/'info'/'man' <command>' to learn more about that command."
echo "A command with (h/i/m) will indicate what is available for that command."
echo "Commands were found on Ubuntu 20.04"
echo "Type 'cnchlg -h' to open the help for 'Conchologia' (NOT IMPLEMENTED)"
echo
echo "aa-remove-unknown            Remove unknown AppArmor profiles (i/m)"
echo "aa-status                    Display various information about the current AppArmor policy. (i/m)"
echo "aa-teardown                  Unload all AppArmor profiles (i/m)"
echo "access.conf                  The login access control table file. (i/m)"
echo "accessdb                     Dumps the contents of a man-db database in a human readable format. (i/m)"
echo "acct                         Process accounting file. (i/m)"
echo "acl                          Access Control Lists (i/m)"
echo "acpid                        Advanced Configuration and Power Interface event daemon (i/m)"
echo "actions                      Independently defined actions in tc. (i/m)"
echo "addgnupghome                 Create .gnupg home directories (i/m)"
echo "addgroup                     Add a group to the system (i/m)"
echo "add-shell                    Add shells to the list of valid login shells (i/m)"
echo "adduser                      Add a user to the system (i/m)"
echo "agetty                       Alternative Linux getty (i/m)"
echo "aio                          POSIX asynchronous I/O overview. (i/m)"
echo "alias                        Define or display aliases. (h)"
echo "alsactl                      Advanced controls for ALSA soundcard driver. (i/m)"
echo "alsainfo                     Command-line utility to gather information about the ALSA subsystem. (i/m)"
echo "alsaucm                      ALSA Use Case Manager (i/m)"
echo "amidi                        Read from and write to ALSA RawMIDI ports (i/m)"
echo "amixer                       Command-line mixer for ALSA soundcard driver (i/m)"
echo "anacron                      Runs commands periodically. (i/m)"
echo "anacrontab                   Configuration file for anacron. (i/m)"
echo "apparmor_parser              Loads AppArmor profiles into the kernel (i/m)"
echo "applygnupgdefaults           Run gpgconf --apply-defaults for all users. (i/m)"
echo "apropos                      Search the manual page names and descriptions. (i/m)"
echo "apt                          Command Line Interface for Package Managment. (i/m)"
echo "aptd                         Package managing daemon proving a D-Bus interface (i/m)"
echo "apt-get                      APT package handling utility -- command-line interface (i/m)"
echo "arch                         Print machine hardware name. (i)"
echo "arp                          Linux ARP kernel module. (i/m)"
echo "arpd                         Userspace arp daemon. (i/m)"
echo "arptables                    ARP table administration (nft-based) (i/m)"
echo "aseqdump                     Show the events received at an ALSA sequencer port (i/m)"
echo "aseqnet                      ALSA sequencer connectors over network (i/m)"
echo "avahi-autoipd                IPv4LL network address configuration daemon (i/m)"
echo "avahi-browse                 Browse for mDNS/DNS-SD services using the Avahi daemon (i/m)"
echo "avahi-daemon                 The Avahi mDNS/DNS-SD daemon. (i/m)"
echo "avahi-resolve                Resolve one or more mDNS/DNS host name(s) to IP address(es) (and vice versa) using the Avahi daemon (i/m)"
echo "awk                          Activates the AWK Interpreter. (i/m)"
echo "aspell                       Interactive spell checker. (i/m)"
echo "aspell-autobuildhash         Autobuilding aspell hash files for some dicts (i/m)"
echo "b2sum                        Print or check BLAKE2 digests. (i)"
echo "badblocks                    Search a device for bad blocks (i/m)"
echo "baobab                       A graphical tool to analyze disk usage (i/m)"
echo "base32                       Base32 encode/decode data. (i)"
echo "base64                       Base64 encode/decode data. (i)"
echo "basename                     Strip directory and suffix. (i)"
echo "bash                         GNU Bourne-Again SHell. (i/m)"
echo "bc                           Arbitrary Precision Calculator Language. (i/m)"
echo "bg                           Move jobs to the background. (h)"
echo "bind                         Set Readline key bindings and variables. (h)"
echo "biosdecode                   BIOS information decoder. (i/m)"
echo "blkdeactivate                Utility to deactivate block devices. (i/m)"
echo "blkdiscard                   Discard sectors on a device. (i/m)"
echo "blkzone                      Run zone command on a device. (i/m)"
echo "blockdev                     Call block device ioctls from the command line (i/m)"
echo "bluetoothd                   Bluetooth daemon (i/m)"
echo "break                        Exit for, while, or until loops. (h)"
echo "bridge                       Show/manipulate bridge addresses and devices (i/m)"
echo "brltty                       Refreshable braille display driver for Linux/Unix. (i/m)"
echo "broadwayd                    Broadway display server (i/m)"
echo "builtin                      Execute shell builtin. (h)"
echo "bunzip2                      A block-sorting file compressor, v1.0.8 (i/m)"
echo "bzcat                        Decompresses files to stdout (i/m)"
echo "bzip2                        File Compressor or Decompressor. (i/m)"
echo "bzip2recover                 Recovers data from damaged bzip2 files (i/m)"
echo "cal                          Displays a calendar and the date of Easter. (i/m)"
echo "calendar                     Reminder service. (i/m)"
echo "calibrate_ppa                pnm2ppa calibration tool (i/m)"
echo "caller                       Return the context of the current subroutine call. (h)"
echo "canberra-gtk-play            Play a sound event (i/m)"
echo "capsh                        Capability shell wrapper (i/m)"
echo "case                         Execute commands based on pattern matching. (h)"
echo "cat                          Concatenate and write files. (i)" 
echo "catman                       Create or update the pre-formatted manual pages (i/m)"
echo "cd                           Change the shell working directory. (h)"
echo "cd-it8                       Color Manager Testing Tool (i/m)"
echo "cfdisk                       Display or manipulate a disk partition table. (i/m)"
echo "cgdisk                       Curses-based GUID partition table (GPT) manipulator (i/m)"
echo "chat                         Automated conversational script with a modem (i/m)"
echo "chattr                       Change file attributes on a Linux file system. (i/m)"
echo "chcon                        Change SELinux CTX of files. (i)"
echo "chcpu                        Configure CPUs (i/m)"
echo "chgpasswd                    Update group passwords in batch mode (i/m)"
echo "chgrp                        Change file groups. (i)"
echo "chmem                        Configure memory (i/m)"
echo "chmod                        Change access permissions. (i)"
echo "chown                        Change file owners and groups. (i)"
echo "chpasswd                     Update passwords in batch mode. (i/m)"
echo "chroot                       Specify the root directory/Run command or interactive shell with special root directory (i/m)"
echo "chsh                         Change login shell (i/m)"
echo "chvt                         Change foreground virtual terminal (i/m)"
echo "ckbcomp                      Compile a XKB keyboard description to a keymap suitable for loadkeys or kbdcontrol. (i/m)"
echo "cksum                        Print POSIX CRC checksum. (i)"
echo "clear                        Clear the terminal screen. (i/m)"
echo "cmp                          Compare 2 files byte by byte. (i)"
echo "col                          Filter reverse line feeds from input (i/m)"
echo "comm                         Compare sorted files by line. (i)"
echo "command                      Execute a simple command or display information about commands. (h)"
echo "compgen                      Display possible completions depending on the options. (h)"
echo "complete                     Specify how arguments are to be completed by Readline. (h)"
echo "compopt                      Modify or display completion options. (h)"
echo "continue                     Resume for, while, or until loops. (h)"
echo "coproc                       Create a coprocess named NAME. (h)"
echo "cp                           Copy files. (i)"
echo "cpp                          The C Preprocessor (i/m)"
echo "cpio                         Copy files to and from archives. (i/m)"
echo "cpgr                         Copy with locking the given file to the group file. (i/m)"
echo "cppw                         Copy with locking the given file to the password file. (i/m)"
echo "cracklib-check               Check passwords using libcrack2 (i/m)"
echo "cracklib-format              Cracklib dictionary utilities (i/m)"
echo "cracklib-packer              Cracklib dictionary utilities (i/m)"
echo "cracklib-unpacker            Cracklib dictionary utilities (i/m)"
echo "crda                         Send to the kernel a wireless regulatory domain for a given ISO / IEC 3166 alpha2 (i/m)"
echo "cron                         Daemon to execute scheduled commands. (i/m)"
echo "crontab                      Maintain crontab files for individual users. (i/m)"
echo "csplit                       Split by context. (i/m)"
echo "ctrlaltdel                   Set the function of the Ctrl-Alt-Del combination (i/m)"
echo "cupsaccept                   Accept jobs sent to a destination (i/m)"
echo "cupsctl                      Configure cupsd.conf options (i/m)"
echo "cupsd                        Cups scheduler (i/m)"
echo "cupsdisable                  Stop printers and classes. (i/m)"
echo "cupsenable                   Start printers and classes. (i/m)"
echo "cupsfilter                   Convert a file to another format using cups filters (deprecated) (i/m)"
echo "cupsreject                   Reject jobs sent to a destination (i/m)"
echo "cups-browed                  A daemon for browsing the Bonjour broadcasts of shared, remote CUPS printers (i/m)"
echo "cut                          Print selected parts of lines. (i)"
echo "date                         Print/set system data and time. (i)"
echo "dbus-run-session             Start a process as a new D-Bus session (i/m)"
echo "dc                           An arbitrary precision calculator. (i/m)"
echo "dconf                        Simple tool for manipulating a dconf database (i/m)"
echo "dd                           Copy and convert a file. (i)"
echo "debugfs                      ext2/ext3/ext4 file system debugger. (i/m)"
echo "declare                      Set variable values and attributes. (h)"
echo "delgroup                     Remove a group from the system (i/m)"                  
echo "deluser                      Remove a user from the system (i/m)"
echo "depmod                       Generate modules.dep and map files. (i/m)"
echo "devdump                      Interactively display the contents of device or filesystem images (i/m)"
echo "devlink                      Devlink tool (i/m)"
echo "df                           Report file system disk usage. (i)"
echo "dhclient                     Dynamic Host Configuration Protocol Client (i/m)"
echo "dhclient-script              DHCP client network configuration script (i/m)"
echo "dh_bash-completion           Install bash completions for package (i/m)"
echo "diff                         Compare 2 files line by line. (i)"
echo "diff3                        Compare 3 files line by line. (i)"
echo "dig                          DNS Lookup Utility. (i/m)"
echo "dircolors                    Color setup for ls. (i)"
echo "dirname                      Strip last file name component. (i)"
echo "dir                          List directories briefly. (i)"
echo "dirs                         Display directory stack. (h)"
echo "disown                       Remove jobs from current shell. (h)"
echo "dmesg                        Print or control the kernel ring buffer. (i/m)"
echo "dmidecode                    DMI table decoder (i/m)"
echo "dmsetup                      Low level logical volume management. (i/m)"
echo "dmstats                      Device-mapper statistics management (i/m)"
echo "dnsdomainname                Show the system's DNS domain name (i/m)"
echo "dnsmasq                      A lightweight DHCP and caching DNS server. (i/m)"
echo "domainname                   Show or set the system's NIS/YP domain name (i/m)"
echo "dosfsck                      Check and repair MS-DOS filesystems (i/m)"
echo "dpkg                         Package Manager for Debian & Ubuntu. (i/m)"
echo "dpkg-deb                     Debian package archive (.deb) manipulation tool (i/m)"
echo "dpkg-preconfigure            Let packages ask questions prior to their installation (i/m)"
echo "dpkg-reconfigure             Reconfigure an already installed package (i/m)"
echo "du                           Report on disk usage. (i)"
echo "dumpe2fs                     Dump ext2/ext3/ext4 filesystem information (i/m)"
echo "ebtables                     Ethernet bridge frame table administration (nft-based)"
echo "echo                         Print a line of text. (h/i/m)"
echo "eject                        Eject removable media. (i/m)"
echo "enable                       Enable and disable shell builtins. (h)"
echo "enc2xs                       Perl Encode Module Generator (i/m)"
echo "env                          Modify the environment. (i)"
echo "eval                         Execute arguments as a shell command. (h)"
echo "evince-thumbnailer           Create png thumbnails from PostScript and PDF documents (i/m)"
echo "exec                         Replace the shell with the given command. (h)"
echo "exit                         Exit the shell (h)"
echo "expand                       Convert tabs to spaces. (i)"
echo "export                       Set export attribute for shell variables. (h)"
echo "expr                         Evaluate expressions. (i)"
echo "e2image                      Save critical ext2/ext3/ext4 filesystem metadata to a file. (i/m)"
echo "e2freefrag                   Report free space fragmentation information. (i/m)"
echo "e2fsck                       Check of Linux ext2/ext3/ext4 file system. (i/m)"
echo "e2label                      Change the label on an ext2/ext3/ext4 filesystem (i/m)"
echo "e2mmpstatus                  Check MMP status of an ext4 filesystem (i/m)"
echo "e2scrub                      Check the contents of a mounted ext[234] filesystem (i/m)"
echo "e2scrub_all                  Check all mounted ext[234] filesystems for errors. (i/m)"
echo "e2undo                       Replay an undo log for an ext2/ext3/ext4 filesystem. (i/m)"
echo "e4crypt                      Ext4 Filesystem Encryption Utility. (i/m)"
echo "e4defrag                     Online defragmenter for ext4 filesystem (i/m)"
echo "factor                       Print prime factors. (i)"
echo "faillock                     Tool for displaying and modifying the authentication failure record files (i/m)"
echo "fallocate                    Preallocate or deallocate space to a file (i/m)"
echo "false                        Do nothing, unsuccessfully. (h/i)"
echo "fatlabel                     Set or get MS-DOS filesystem label. (i/m)"
echo "fc                           Display or execute commands from the history list. (h)"
echo "fc-scan                      Scan font files or directories (i/m)"
echo "fdformat                     Low-level format a floppy disk. (i/m)"
echo "fdisk                        Manipulate disk partition table. (i/m)"
echo "fg                           Move job to the foreground. (h)"
echo "file                         Determine file type. (i/m)"
echo "filefrag                     Report on file fragmentation (i/m)"
echo "file2brl                     Translate an xml or a text file into an embosser-ready braille file (i/m)"
echo "find                         Finding and acting on files. (i)"
echo "findfs                       Find a filesystem by label or UUID. (i/m)"
echo "fixparts                     MBR partition table repair utility. (i/m)"
echo "fmt                          Reformat paragraph text. (i)"
echo "fold                         Wrap long input lines. (i)"
echo "for                          Execute commands for each member in a list. (h)"
echo "fprintd                      Fingerprint management daemon, and test applications (i/m)"
echo "free                         Display amount of free and used memory in the system. (i/m)"
echo "fsck                         Check and repair a Linux filesystem. (i/m)"
echo "fsck.cramfs                  Fsck compressed ROM file system (i/m)"
echo "fsck.fat                     Check and repair MS-DOS filesystems. (i/m)"
echo "fsck.minix                   Check consistency of Minix filesystem (i/m)"
echo "fsfreeze                     Suspend access to a filesystem (Ext3/4, ReiserFS, JFS, XFS) (i/m)"
echo "fstab-decode                 Run a command with fstab-encoded arguments (i/m)"
echo "fstrim                       Discard ununsed blocks on a mounted filesystem (i/m)"
echo "ftp                          Internet file transfer program. (i/m)"
echo "function                     Define shell function. (h)"
echo "fuse                         Format and options for the fuse file systems (i/m)"
echo "fuser                        Identify processes using files or sockets. (i/m)"
echo "gcore                        Generate a core file or a running program (i/m)"
echo "gdisk                        Interactive GUID partition table (GPT) manipulator (i/m)"
echo "gdm3                         GNOME Display Manager (i/m)"
echo "genisoimage                  Create ISO9660/Joliet/HFS filesystem with optional Rock Ridge attributes (i/m)"
echo "genl                         Generic netlink utility frontend (i/m)"
echo "getcap                       Examine file capabilities. (i/m)"
echo "getopts                      Parse option arguments. (h)"
echo "getpcaps                     List Process Capabilities. (i/m)"
echo "gio                          GIO commandline tool (i/m)"
echo "gpg                          OpenPGP encryption and signing tool (i/m)"
echo "grep                         Print lines that match patterns. (i/m)"
echo "grotty                       Groff driver for typewriter-like devices (i/m)"
echo "groupadd                     Create a new group. (i/m)"
echo "groupdel                     Delete a group. (i/m)"
echo "groupmems                    Administer members of a user's primary group (i/m)"
echo "groupmod                     Modify a group definition on the system. (i/m)"
echo "groups                       Print group names a user is in. (i)"
echo "grpck                        Verify integrity of group files. (i/m)"
echo "grpconv                      Convert to and from shadow passwords and groups. (i/m)"
echo "grpunconv                    Convert to and from shadow passwords and groups. (i/m)"
echo "grub-bios-setup              Set up a device to boot using GRUB (i/m)"
echo "grub-install                 Install GRUB to a device. (i/m)"
echo "grub-macbless                Bless a mac file/directory (i/m)"
echo "grub-mkconfig                Generate a GRUB configuration file (i/m)"
echo "grub-mkdevicemap             Make a device map file automatically. (i/m)"
echo "grub-mkimage                 Make a bootable image of GRUB (i/m)"
echo "grub-mount                   Export GRUB filesystem with FUSE (i/m)"
echo "grub-probe                   Probe device information for GRUB (i/m)"
echo "gnome-language-selector      Graphical language selection utility (i/m)"
echo "gst-discoverer-1.0           Display file metadata and stream information (i/m)"
echo "gst-play-1.0                 Simple command line playback testing tool (i/m)"
echo "gtk-builder-tool             GtkBuilder file utility (i/m)"
echo "gtk-query-settings           Utility to print name and value of all GtkSettings properties (i/m)"
echo "gunzip                       Decompression. (i)"
echo "gzexe                        Compress executables. (i)"
echo "gzip                         Compress or expand files. (i/m)"
echo "halt                         Halt, power-off or reboot the machine. (i/m)"
echo "hash                         Remember or display program locations. (h)"
echo "hdparm                       Get/Set SATA/IDE device parameters (i/m)"
echo "head                         Output the first part of files. (i)"
echo "help                         Display information about builtin commands. (h)"
echo "history                      Display a history of inputted commands. (h/i)"
echo "host                         DNS lookup utility (i/m)"
echo "hostid                       Print numeric host identifier. (i)"
echo "hostname                     Print or set systemname. (i/m)"
echo "hp-plugin                    HP Proprietary Plugin Download and Install Utility (i/m)"
echo "hwclock                      Time clocks utility. (i/m)"
echo "iconv                        Convert text from one character encoding to another (i/m)"
echo "iconvconfig                  Create iconv module configuration cache (i/m)"
echo "id                           Print user identity. (i)"
echo "iecset                       Set or dump IEC958 status bits (i/m)"
echo "if                           Execute commands based on conditional. (h)"
echo "init                         Systemd system and service manager (i/m)"
echo "install                      Copy files and set attributes. (i)"
echo "installkernel                Install a new kernel image (i/m)"
echo "install-sgmlcatalog          Maintain transitional SGML catalog (i/m)"
echo "invoke-rc.d                  Executes System-V style init script actions. (i/m)"
echo "ip                           Show/manipulate routing, network devices, interfaces and tunnels. (i/m)"
echo "ippeveprinter                An ipp everywhere printer application for cups (i/m)"
echo "ippusbxd                     Communication driver for IPP-over-USB class printers. (i/m)"
echo "iptables                     Administration tool for IPv4 qpacket filtering and NAT (i/m)"
echo "iptables-save                Dump iptables rules. (i/m)"
echo "ip6tables                    Administration tool for IPv6 packet filtering and NAT (i/m)"
echo "ip6tables-save               Dump ip6tables rules. (i/m)"
echo "irqbalance                   Distribute hardware interrupts across processors on a multiprocessor system. (i/m)"
echo "irqbalance-ui                User interface for irqbalance (i/m)"
echo "isodump                      Interactively display the contents of iso9660 images to verify integrity (i/m)"
echo "isoinfo                      Utility to perform directory like listings of iso9660 images. (i/m)"
echo "isosize                      Output the length of an iso9660 filesystem. (i/m)"
echo "isovfy                       Verify the integrity of an iso9660 image. (i/m)"
echo "ispell-autobuildhash         Autobuilding the ispell hash file for some dicts (i/m)"
echo "iucode_tool                  Tool to manipulate Intel IA-32/X86-64 microcode bundles. (i/m)"
echo "iw                           Show / manipulate wireless devices and their configuration (i/m)"
echo "iwconfig                     Configure a wireless network interface (i/m)"
echo "iwevent                      Display Wireless Events generated by drivers and setting changes (i/m)"
echo "iwgetid                      Report ESSID, NWID or AP/Cell Address of wireless network (i/m)"
echo "iwlist                       Get more detailed wireless information from a wireless interface. (i/m)"
echo "iwpriv                       Configure optionals (private) parameters of a wireless network interface (i/m)"
echo "iwspy                        Get wireless statistics from specific nodes. (i/m)"
echo "jobs                         Display status of jobs. (h)"
echo "join                         Join lines on a common field. (i)"
echo "kbdrate                      Reset the keyboard repeat rate and delay time. (i/m)"
echo "kerneloops                   Program to collect and submit kernel oopses to oops.kernel.org (i/m)"
echo "kill                         Send a signal to processes. (h/i)" 
echo "killall                      Kill processes by name. (i/m)"
echo "killall5                     Send a signal to all processes. (i/m)"
echo "lcf                          Determine which of the historical versions of a config is installed (i/m)"
echo "ldattach                     Attach a line discipline to a serial line (i/m)"
echo "ldconfig                     Configure dynamic linker run-time bindings (i/m)"
echo "less                         Opposite of more. (i/m)"
echo "lesskey                      Specify key bindings for less (i/m)"
echo "let                          Evaluate arithmetic expressions. (h)" 
echo "libreoffice                  LibreOffice office suite (i/m)"
echo "libwacom-list-local-devices  Utility to list tablet devices (i/m)"
echo "link                         Make hard links between files. (i)"
echo "listres                      List resources in widgets (i/m)"
echo "lsmod                        Show the status of modules in the Linux Kernel (i/m)"
echo "ln                           Make links between files. (i)"
echo "local                        Define local variables. (h)"
echo "locale                       Get locale-specific information (i/m)"
echo "localedef                    Compile locale definition files (i/m)"
echo "locale-gen                   Generates localisation files from templates (i/m)"
echo "locate                       Finding files in a database. (i)"
echo "logger                       Enter messages into the system log (i/m)"
echo "login                        Begin session on the system (i/m)"
echo "logname                      Print current login name. (i)"
echo "logout                       Exit a login shell. (h)"
echo "logrotate                    Rotates, compresses, and mails system logs. (i/m)"
echo "logsave                      Save the output of a command in a logfile (i/m)"
echo "look                         Display lines beginning with a given string. (i/m)"
echo "losetup                      Set up and control loop devices (i/m)"
echo "lp                           Print files (i/m)"
echo "lpadmin                      Configure cups printers and classes (i/m)"
echo "lpc                          line printer control program. (i/m)"
echo "lpinfo                       Show available devices or drivers (deprecated) (i/m)"
echo "lpmove                       Move a job or all jobs to a new destination (i/m)"
echo "lpq                          Show printer queue status (i/m)"
echo "lprm                         Cancel print jobs. (i/m)"
echo "ls                           List directory contents. (i)"
echo "lsattr                       List file attributes on a Linux second extended file system. (i/m)"
echo "lsblk                        List block devices. (i/m)"
echo "lsof                         List open files. (i/m)"
echo "lspci                        List all PCI devices. (i/m)"
echo "lspcmcia                     Display extended PCMCIA debugging information. (i/m)"
echo "lsusb                        List USB devices (i/m)"
echo "ltrace                       A library call tracer. (i/m)"
echo "lwp-request                  Simple command line user agent (i/m)"
echo "lz                           Gunzips and shows a listing of a gzip'd tar'd archive (i/m)"
echo "make-ssl-cert                Debconf wrapper for openssl (i/m)"
echo "man                          An interface to the system reference manuals. (i/m)"
echo "mapfile                      Read lines from the standard input into an indexed array variable. (h)"
echo "mbadblocks                   Tests a floppy disk, and marks the bad blocks in the FAT (i/m)"
echo "mcheck                       Verify all files on an MS-DOS formatted disk (i/m)"
echo "mcookie                      Generate magic cookies for xauth. (i/m)"
echo "md5sum                       Print or check MD5 digests. (i)"
echo "mformat                      Add an MSDOS filesystem to a low-level formatted floppy disk (i/m)"
echo "mkdir                        Create directories. (i)"
echo "mke2fs                       Create an ext2/ext3/ext4 filesystem. (i/m)"
echo "mkfifo                       Create FIFOs (named pipes). (i)"
echo "mkfontdir                    Create an index of X font files in a directory (i/m)"
echo "mkfs                         Build a Linux filesystem (i/m)"
echo "mkfs.bfs                     Make an SCO bfs filessytem (i/m)"
echo "mkfs.cramfs                  Make compressed ROM file system (i/m)"
echo "mkfs.fat                     Create an MS-DOS filesystem under Linux. (i/m)"
echo "mkfs.minix                   Make a Minix filesystem. (i/m)"
echo "mkhomedir_helper             Helper binary that creates home directories (i/m)"
echo "mkisofs                      Create ISO9660/Joliet/HFS filesystem with optional Rock Ridge attributes. (i/m)"
echo "mkinitramfs                  Low-level tool for generating an initramfs image (i/m)"
echo "mklost+found                 Create a lost+found directory on a mounted Linux second extended file system (i/m)"
echo "mknod                        Create special files. (i)"
echo "mkntfs                       Create an NTFS file system (i/m)"
echo "mkswap                       Set up a Linux swap area (i/m)"
echo "mktemp                       Create temporary files. (i)"
echo "mmount                       Mount an MSDOS disk (i/m)"
echo "ModemManager                 Mobile broadband modem management daemon (i/m)"
echo "modinfo                      Show information about a Linux Kernel module (i/m)"
echo "modprobe                     Add and remove modules from the Linux Kernel (i/m)"
echo "more                         File perusal filter for crt viewing. (i/m)"
echo "mount                        Mount a filesystem. (i/m)"
echo "mshortname                   Shows short name of a file (i/m)"
echo "mtools                       Utilities to access DOS disks in Unix. (i/m)"
echo "mtoolstest                   Tests and displays the configuration (i/m)"
echo "mtr                          A network diagnostic tool. (i/m)"
echo "mv                           Rename files. (i)"
echo "namei                        Follow a pathname until a terminal point is found (i/m)"
echo "nano                         Open the NANO text editor. (i/m)"
echo "nautilus                     A file manager for GNOME. (i/m)"
echo "nc                           Arbitrary TCP and UDP connections and listens. (i/m)"
echo "ncal                         Displays a calendar and the date of Easter (i/m)"
echo "neqn                         Format equations for ASCII output (i/m)"
echo "netplan                      YAML network configuration abstraction for various backends (i/m)"
echo "NetworkManager               Network management daemon. (i/m)"
echo "newusers                     Update and create new users in batch (i/m)"
echo "nfnl_osf                     OS fingerprint loader utility (i/m)"
echo "nice                         Modify niceness. (i)"
echo "nisdomainname                Show or set the system's NIS/YP domain name (i/m)"
echo "nl                           Number lines and write files. (i)"
echo "nm-connection-editor         Network connection editor for NetworkManager (i/m)"
echo "nohup                        Immunize to hangups. (i)"
echo "nologin                      Politely refuse a login (i/m)"
echo "notify-send                  A program to send desktop notifications. (i/m)"
echo "nproc                        Print the number of processors. (i)"
echo "nslookup                     Query Internet name servers interactively. (i/m)" 
echo "nstat                        Network statistics tools. (i/m)"
echo "ntfsclone                    Efficiently clone, image, restore or rescue an NTFS (i/m)"
echo "ntfscluster                  Identify files in a specified region of an NTFS volume. (i/m)"
echo "ntfscp                       Copy file to an NTFS volume. (i/m)"
echo "ntfslabel                    Display/change the label on an ntfs file system (i/m)"
echo "ntfsresize                   Resize an NTFS filesystem without data loss (i/m)"
echo "ntfsundelete                 Recover a deleted file from an NTFS volume. (i/m)"
echo "ntfs-3g                      Third Generation Read/Write NTFS Driver. (i/m)"
echo "numfmt                       Reformat numbers. (i)"
echo "od                           Dump files in octal, etc. (i)"
echo "on_ac_power                  Test whether computer is running on AC power (i/m)"
echo "openvpn                      Secure IP tunnel daemon. (i/m)"
echo "orca                         A scriptable screen reader (i/m)"
echo "ownership                    Compaq ownership tag retriever (i/m)"
echo "pacat                        Play back or record raw or encoded audio streams on a PulseAudio sound server (i/m)"
echo "padsp                        PulseAudio OSS Wrapper (i/m)"
echo "pam-auth-update              Manage PAM configuration using packaged profiles. (i/m)"
echo "pam_getenv                   Get environment variables from /etc/environment (i/m)"
echo "pam_tally                    The login counter (tallying) module (i/m)"
echo "pam_timestamp_check          Check to see if the default timestamp is valid. (i/m)"
echo "paperconfig                  Configure the system default paper size (i/m)"
echo "parted                       A Partition Manipulation Program. (i/m)"
echo "partprobe                    Inform the OS of partition table changes. (i/m)"
echo "passwd                       Change user password (i/m)"
echo "paste                        Merge lines of files. (i)"
echo "patch                        Apply a patch to a file. (i)"
echo "pathchk                      Check file name portability. (i)"
echo "pccardctl                    PCMCIA card control utility. (i/m)"
echo "pdfsig                       Portable Docuemtn Format (PDF) digital signatures tool (i/m)"
echo "pfbtopfa                     Convert Postscript .pfb fonts to .pfa format using ghostscript (i/m)"
echo "ping                         Send ICMP ECHO_REQUEST to network hosts. (i/m)"
echo "pivot_root                   Change the root filesystem (i/m)"
echo "pkcheck                      Check whether a process is authorized (i/m)"
echo "pkill                        Look up or signal processes based on name and other attributes. (i/m)"
echo "plog                         Lists the log of PPP connections (i/m)"
echo "plymouthd                    The plymouth daemon (i/m)"
echo "poff                         Shuts down a PPP connection (i/m)"
echo "pon                          Starts up a PPP connection (i/m)"
echo "popd                         Remove directories from stack. (h)"
echo "popularity-contest           List the most popular Debian packages (i/m)"
echo "poweroff                     Power-off the machine (i/m)"
echo "pppd                         Point-to-Point Protocol Daemon. (i/m)"
echo "pppdump                      Convert PPP record file to readable format. (m)"
echo "pppstats                     Print PPP statistics. (i/m)"    
echo "pptp                         PPTP driver (i/m)"
echo "pptpsetup                    Point-to-Point Tunneling Protocol setup. (i/m)"
echo "pr                           Convert text files for printing. (h/m)"
echo "printenv                     Print environment variables. (i)"
echo "printf                       Format and print data. (h/i)"
echo "pr                           Paginate or columnate files. (i)"
echo "ps                           Report a snapshot of the current processes. (i/m)"
echo "ptargrep                     Apply pattern matching to the contents of files in a tar archive (i/m)"
echo "ptx                          Produce permuted indexes. (i)"
echo "pushd                        Add directories to stack. (h)"
echo "pwck                         Verify integrity of password files (i/m)"
echo "pwconv                       Convert to and from shadow passwords and groups. (i/m)"
echo "pwd                          Print working directory. (h/i)"
echo "pwunconv                     Convert to and from shadow passwords and groups. (i/m)"
echo "ram                          Ram disk device. (i/m)"
echo "raw                          Bind a Linux raw character device (i/m)"
echo "rctest                       RFCOMM testing (i/m)"
echo "read                         Read a line from the standard input and split it into fields. (h)"
echo "readarray                    Read lines from a file into an array variable. (h)"
echo "readlink                     Print referent of a symlink. (i)"
echo "readonly                     Mark shell variables as unchangeable. (h)"
echo "readprofile                  Read kernel profiling information. (i/m)"
echo "realpath                     Print resolved file names. (i)"
echo "reboot                       Halt, power-off or reboot the machine. (i/m)"
echo "regdbdump                    Parse and print out regulatory rules file. (i/m)"
echo "remove-default-wordlist      Remove default wordlist (i/m)"
echo "rename                       Rename files. (i/m)"
echo "renice                       Alter priority of running processes. (i/m)"
echo "reset                        Terminal initialization. (i/m)"
echo "resize2fs                    ext2/ext3/ext4 file system resizer (i/m)"
echo "return                       Return from a shell function. (h)"
echo "rev                          Reverse lines characterwise. (i/m)"
echo "rfkill                       Tool for enabling and disabling wireless devices. (i/m)"
echo "rhythmbox                    Music player and library for tagged files using GStreamer (i/m)"
echo "rmdir                        Remove empty directories. (i)"
echo "rm                           Remove files. (i)"
echo "rmt                          Remote magnetic tape server (i/m)"
echo "rmmod                        Simple program to remove a module from the Linux Kernel (i/m)"
echo "rmt                          Remote magnetic tape server (i/m)"
echo "rnano                        A restricted nano (i/m)"
echo "rsync                        A fast, versatile, remote (and local) file-copying tool. (i/m)"
echo "rsyslogd                     Reliable and extended syslogd (i/m)"
echo "rtacct                       Network statistics tools. (i/m)"
echo "rtcwake                      Enter a system sleep state until specified wakeup time. (i/m)"
echo "rtkitctl                     Realtime Policy and Watchdog daemon control (i/m)"
echo "rtmon                        Listens to and monitors RTnetlink (i/m)"
echo "runcon                       Run in specified SELinux CTX. (i)"
echo "runlevel                     Print previous and current SysV runlevel (i/m)"
echo "runuser                      Run a command with a substitute user and group ID (i/m)"
echo "run-mailcap                  Execute programs via entries in the mailcap file (i/m)"
echo "scp                          OpenSSH secure file copy. (i/m)"
echo "saned                        SANE network daemon (i/m)"
echo "scanimage                    Scan an image (i/m)"
echo "sdiff                        Merge 2 files side-by-side (i)"
echo "sed                          Stream editor for filtering and transforming text. (i/m)"
echo "seg                          Print numeric sequences. (i)"
echo "select                       Select words from a list and execute commands. (h)"
echo "select-default-ispell        Select default ispell dictionary (i/m)"
echo "select-default-wordlist      Select default wordlist (i/m)"
echo "select-editor                Select your default sensible-editor from all installed editors (i/m)"
echo "seq                          Prints a sequence of numbers to standard output. (i/m)"
echo "service                      Run a System V init script (i/m)"
echo "session-migration            Migrate in user session settings. (i/m)"
echo "set                          Set or unset values of shell options and positional parameters. (h)"
echo "setarch                      Change reported architecture in new program environment and/or set personality flags (i/m)"
echo "setcap                       Set file capabilities. (i/m)"
echo "setpci                       Configure PCI devices (i/m)"
echo "setsid                       Run a program in a new session (i/m)"
echo "setvesablank                 Turn VESA screen blanking on or off (i/m)"
echo "setvtrgb                     Customize the console color map (i/m)"
echo "sfdisk                       Display or manipulate a disk partition table. (i/m)"
echo "sftp                         OpenSSH secure file transfer. (i/m)"
echo "sgdisk                       Command-line GUID partition table (GPT) manipulator for Linux and Unix (i/m)"
echo "sha1sum                      Print or check SHA-1 digests. (i)"
echo "sha2                         Print or check SHA-2 digests. (i)"
echo "shift                        Shift positional parameters. (h)"
echo "shopt                        Set and unset shell options. (h)"
echo "shred                        Remove files more securely. (i/m)"
echo "shuf                         Shuffling text files. (i)"
echo "shutdown                     Halt, power-off or reboot the machine. (i/m)"
echo "sleep                        Delay for a specified time. (i)"
echo "snap                         Tool to interact with snaps (i/m)"
echo "sort                         Sort text files. (i)"
echo "source                       Execute commands from a file in the current shell. (h)"
echo "spice-vdagentd               Spice guest agent daemon (i/m)"
echo "split                        Split into pieces. (i)"
echo "ss                           Open Socket Statistics. (i)"
echo "ssh                          OpenSSH remote login client. (i/m)"
echo "ssh-agent                    OpenSSH authentication agent (i/m)"
echo "ssh-argv0                    Replaces the old ssh command-name as hostname handling (i/m)"
echo "ssh-keyscan                  Gather SSH public keys from servers (i/m)"
echo "start-stop-daemon            Start and stop system daemon programs (i/m)"
echo "stat                         Report file(system) status. (i)"
echo "stdbuf                       Modify stdio buffering. (i)"
echo "strace                       Trace system calls and signals. (i/m)"
echo "stty                         Print/change terminal settings. (i)"
echo "su                           Run a command with substitute user and group ID (i/m)"
echo "sudo                         Execute a command as another user. (i/m)"
echo "sulogin                      Single-user login (i/m)"
echo "sum                          Print traditional checksum. (i)"
echo "suspend                      Suspend shell execution. (h)"
echo "swaplabel                    Print or change the label or UUID of a swap area (i/m)"
echo "swapoff                      Disable devices and files for paging and swapping (i/m)"
echo "swapon                       Enable devices and files for paging and swapping (i/m)"
echo "switch_root                  Switch to another filesystem as the root of the mount tree. (i/m)"
echo "sync                         Synchronize memory to disk. (i)"
echo "sysctl                       Configure kernel parameters at runtime. (i/m)"
echo "systemd                      Systemd system and service manager (i/m)"
echo "systemd-ask-password         Query the user for a system password (i/m)"
echo "systemd-cat                  Connect a pipeline or program's output with the journal (i/m)"
echo "systemd-cgls                 Recursively show control group contents (i/m)"
echo "systemd-path                 List and query system and user paths (i/m)"
echo "tac                          Reverse files. (i)"
echo "tail                         Output the last part of files. (i)"
echo "tar                          An archiving utility. (i/m)"
echo "tarcat                       Concatenates the pieces of a GNU tar multi-volume archive. (i/m)"
echo "tc                           Show/manipulate traffic control settings. (i/m)"
echo "tcpdump                      Dump traffic on a network. (i/m)"
echo "tee                          Redirect to multiple files. (i)"
echo "telinit                      Change SysV runlevel (i/m)"
echo "test                         File/string tests. (h/i)"
echo "thermald                     Start Linux thermal daemon (i/m)"
echo "time                         Run programs and summarize system resource usage. (h/i)"
echo "timeout                      Run with time limit. (i)"
echo "times                        Display process times. (h)"
echo "tipc                         A TIPC configuration and management tool. (i/m)"
echo "toe                          Table of (terminfo) entries (i/m)"
echo "top                          Display Linux processes. (i/m)"
echo "touch                        Change file timestamps. (i)"
echo "tput                         Initialize a terminal or query terminfo database. (i/m)"
echo "tr                           Translate characters. (i)"
echo "trap                         Trap signals and other events. (h)"
echo "true                         Do nothing, successfully. (h/i)"
echo "truncate                     Shrink/extend size of a file. (i)"
echo "tsort                        Topological sort. (i)"
echo "tty                          Print terminal name. (i)"
echo "tune2fs                      Adjust tunable filesystem parameters on ext2/ext3/ext4 filesystems. (i/m)"
echo "type                         Display information about command type. (h)"
echo "typeset                      Set variable values and attributes. (h)"
echo "ubuntu-advantage             Manage Ubuntu Advantage services from Canonical"
echo "ucfr                         Update Configuration File Registry: associate packages with configuration files (i/m)"
echo "ufw                          Program for managing a netfilter firewall (i/m)"
echo "ulimit                       Modify shell resource limits. (h)"
echo "umask                        Display or set file mode mask. (h)"
echo "umount                       Unmount file systems. (i/m)"
echo "umount.udisks2               Unmount file systems that have been moutned by UDisks2 (i/m)"
echo "unalias                      Remove each NAME from the list of defined aliases. (h)"
echo "uname                        Print system information. (i)"
echo "unexpand                     Convert spaces to tabs. (i)"
echo "unicode_start                Put keyboard and console in unicode mode (i/m)"
echo "units                        Decimal and binary prefixes. (i/m)"
echo "uniq                         Uniquify files. (i)"
echo "unix_chkpwd                  Helper binary that verifies the password of a given user (i/m)"
echo "unix_update                  Helper binary that updates the password of a given user (i/m)"
echo "unlink                       Removal via unlink(2). (i)"
echo "unset                        Unset values and attributes of shell variables and functions. (h)"
echo "unshare                      Run program with some namespaces unshared from parent. (i/m)"
echo "until                        Execute commands as long as a test does not succeed. (h)"
echo "updatedb                     Building the locate database. (i)"
echo "update-binfmts               Maintain registry of executable binary formats. (i/m)"
echo "update-ca-certificates       Update /etc/ssl/certs and ca-certificates.crt (i/m)"
echo "update-catalog               Create or update entry in SGML catalog file (i/m)"
echo "update-cracklib              Regenerate cracklib dictionary (i/m)"
echo "update-default-aspell        Rebuild aspell database and emcasen stuff (i/m)"
echo "update-default-ispell        Update default ispell dictionary (i/m)"
echo "update-default-wordlist      Update default wordlist (i/m)"
echo "update-dictcommon-aspell     Rebuild aspell database and emacsen stuff (i/m)"
echo "update-dictcommon-hunspell   Rebuild hunspell database and emacsen stuff (i/m)"
echo "update-fonts-dir             Compile fonts.dir files (i/m)"
echo "update-fonts-scale           Generate fonts.scale files (i/m)"
echo "update-grub                  Stub for grub-mkconfig (i/m)"
echo "update-icon-caches           Update wrapper script for the icon caches (i/m)"
echo "update-inetd                 Create, remove, enable or disable entry /etc/inetd.conf (i/m)"
echo "update-info-dir              Update or create index file from all installed info files in directory (i/m)"
echo "update-initramfs             Generate an initramfs image (i/m)"
echo "update-locale                Modify global locale settings (i/m)"
echo "update-mime                  Create or update MIME information (i/m)"
echo "update-mime-database         A program to build the Shared MIME-Info database cache (i/m)"
echo "update-passwd                Safely update /etc/passwd, /etc/shadow and /etc/group (i/m)"
echo "update-pciids                Download new version of the PCI ID list (i/m)"
echo "update-xmlcatalog            Maintain XML catalog files (i/m)"
echo "uptime                       Print uptime and load. (i)"
echo "usbmuxd                      Expose a socket to multiplex connections from and to iOS devices. (i/m)"
echo "usb_modeswitch               Control the mode of 'multi-state' USB devices. (i/m)"
echo "useradd                      Create a new user or update default new user information. (i/m)"
echo "userdel                      Delete a user account and related files. (i/m)"    
echo "usermod                      Modify a user account. (i/m)"
echo "users                        Print current user names. (i)"
echo "uuidd                        UUID generation daemon. (i/m)"
echo "validlocale                  Test if a given locale is available. (i/m)"
echo "variables                    Common shell variable names and usage. (h)"
echo "vcstime                      Show time in upper right hand corner of the console screen (i/m)"
echo "vdir                         List directories verbosely. (i)"
echo "viewres                      Graphical class browser for Xt (i/m)"
echo "vim                          Open the VIM Text Editor. (i/m)"
echo "vipw                         Edit the password, group, shadow-password or shadow-group file (i/m)"
echo "vigr                         Edit the password, group, shadow-password or shadow-group file (i/m)"
echo "visudo                       Edit the sudoers files. (i/m)"
echo "vmstat                       Report virtual memory statistics. (i/m)"
echo "volname                      Return volume name (i/m)"
echo "vpddecode                    VPD structure decoder. (i/m)"
echo "w                            Show who is logged on and what they are doing. (i/m)"
echo "wait                         Wait for job completion and return exit status. (h)"
echo "watch                        Execute a program periodically, showing output fullscreen. (i/m)"
echo "watchgnupg                   Read and print logs from a socket (i/m)"
echo "wc                           Line, word, and byte counts. (i)"
echo "wget                         The non-interactive network downloader. (i/m)"
echo "whereis                      Locate the binary, source, and manual page files for a command. (i/m)"
echo "which                        Locate a command. (i/m)"
echo "while                        Execute commands as long as a test succeeds. (h)"
echo "who                          Print who is logged in. (i/m)"
echo "whoami                       Print effective user ID. (i)"
echo "wipefs                       Wipe a signature from a device. (i/m)"
echo "word-list-compress           Word list compressor/decompressor for GNU Aspell (i/m)"
echo "wpa_cli                      WPA command line client (i/m)"
echo "wpa_supplicant               Wi-Fi Protected Access client and IEEE 802.1X supplicant (i/m)"
echo "update-rc.d                  Install and remove System-V style init script links. (i/m)"
echo "write                        Send a message to another user. (i/m)"
echo "xargs                        Operating on many files. (i)"
echo "xclock                       Analog / digital clock for X (i/m)"
echo "xdg-email                    Command line tool for sending mail using the user's preferred e-mail composer (i/m)"
echo "xdg-open                     Opens a file or URL in the user's preferred application. (i/m)"
echo "xedit                        Simple text editor for X (i/m)"
echo "xfd                          Display all the characters in an X font. (i/m)"
echo "xload                        System load average display for X (i/m)"
echo "xlsfonts                     Server font list displayer for X (i/m)"
echo "xtables-nft                  Iptables using nftables kernel api (i/m)"
echo "xwd                          Dump an image of an X window (i/m)"
echo "xxd                          Make a hexdump or do the reverse. (i/m)"
echo "xz                           Compress or decompress .xz and .lzma files. (i/m)"
echo "yelp                         Browse system documentation (i/m)"
echo "yes                          Press a string indefinitely. (i)"
echo "ypdomainname                 Show or set the system's NIS/YP domain name (i/m)"
echo "zcat                         Decompression to stdout. (i)"
echo "zdiff                        Compare compressed files. (i)"
echo "zforce                       Force .gz extension on files. (i)"
echo "zgrep                        Search compressed files. (i)"
echo "zic                          Timezone compiler (i/m)"
echo "zip                          Package and compress (archive) files. (i/m)"
echo "zipgrep                      Search files in a ZIP archive for lines matching a pattern (i/m)"
echo "zmore                        Decompression output by pages. (i)"
echo "zramctl                      Set up and control zram devices. (i/m)"
echo 
